WIP
htmlacademy-ecmascript/1018179-cinemaddict-14 pull request #5
Opened 2021-04-12 19:49 UTC by PavelCraze

2021-04-14 20:16 UTC, andreevsm requested changes

2021-04-14 20:16 UTC, andreevsm commented on src/main.js
> +const basicMarkup = new Markup();
Не совсем понятно, что такое Markup
Если это контейнер для остального контента, то давай так и назовем)

2021-04-14 20:16 UTC, andreevsm commented on src/main.js
> +  const filmDetails = new Popup(film);
Тут тоже не понятно - это popup или FilmDetails? Давай к одному виду приведем

Ну и старайся называть переменную согласно экземпляру класса, то есть класс `Card` лучше тоже назвать `FilmCard`

2021-04-14 20:16 UTC, andreevsm commented on src/main.js
> +  const replaceFilmCardToDetails = () => {
А зачем вложенная функция? Давай вынесем и будем просто передавать элемент в нее
У тебя эта функция является сайд эффектом - то есть при определенном действии ты делаешь что-то с глобальной версткой, поэтому не зачем хранить эти функции внутри каждого фильма)

2021-04-14 20:16 UTC, andreevsm commented on src/main.js
> +  document.addEventListener(`keydown`, function (evt) {
Замени на строчную функцию плиз)

2021-04-14 20:16 UTC, andreevsm commented on src/main.js
> +const renderFilmCards = (markup, filmsArray) => {
Есть критерий, согласно которому плохая практика называть переменные с типами данных, то есть лучше `filmsArray` заменить на просто `films`
Ну и на будущее тоже имей ввиду)

2021-04-14 20:16 UTC, andreevsm commented on src/main.js
> +  const listEmpty = new Empty();
Давай тогда класс тоже назовем ListEmpty, чтобы сходу было понятно, за что он отвечает
А то просто Empty не сразу понятно)

2021-04-15 16:10 UTC, PavelCraze commented on src/main.js
> +const renderFilmCards = (markup, filmsArray) => {
здесь линтер начал ругаться на films, поэтому сделал filmsArray)

2021-04-15 21:58 UTC, merged